### ISSUE TITLE
.bottom(by: view._safeAreaLayoutGuide) but with an offset

### ISSUE THREAD

**Issue by ServusJon** [pisces/SimpleLayout#18]
Hey,

how can I set an offset when I use _safeAreaLayoutGuide?

**Comment by pisces** [comment]
Hi.
try like this~

yourView.layout
    .top(by: view._safeAreaLayoutGuide, 100)
    .leading()
    .trailing()
    .bottom(by: view._safeAreaLayoutGuide, -100)

**Comment by ServusJon** [comment]
Perfect!
